spring:
  profiles:
    active: local # 기본 환경 선택

---
spring: 
  profiles: local
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: blog
    password: blog
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1;